import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Image from 'next/image'
import Footer from '@/components/Footer'


export default function Home() {

  return (
    <>
      <Head>
        <title>X. It's what's happening / X </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>

        <div className={styles.twitterLogo}>
          <Image src="/images/twitter logo.png" alt="Xlogo" width={200} height={200} priority/>
        </div>

        <div className={`${styles.content}`}>

          <h1 className={`${styles.h1}`}>Happening now</h1>
          <br/>
          <h2 className={`${styles.h2}`}>Join today.</h2>

          <button className={styles.button} onClick={() => console.log("Google long in")}>
            <Image className={styles.googleLogo} src="/images/google logo.png" width={23} height={23} alt='Google'/>
            <span className={styles.googleSignUp}>Sign up with Google</span>
          </button>
          <br/>
          <button className={styles.button} onClick={() => console.log("Apple log in")}>
            <Image className={styles.appleLogo} src="/images/apple logo.png" width={23} height={23} alt='Apple'/>
            <span className={styles.appleSignUp}>Sign up with Apple</span>
          </button>

            <p className={styles.or}>or </p>

            <Button title="Create account" text={"var(--white-text)"} color={"var(--blue)"}/>
          
            <p className={styles.terms}>
            By signing up, you agree to the <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a>, including <a href="#">Cookie Use.</a>
            </p>

            <br/>
            <h3 className={styles.h3}>Already have an account?</h3>
          <button className={styles.button} onClick={() => console.log("Signing in")}>
            <span className={styles.signIn}>Sign in</span>
          </button>
        </div>


    


      </main>        
      <Footer text='About'/>
      <Footer text='Download the X app'/>
      <Footer text='Helper Center'/>
      <Footer text='Terms of Service'/>
      <Footer text='Privacy Policy'/>
      <Footer text='Cookie Policy'/>
      <Footer text='Accesibility'/>
      <Footer text='Ads info'/>
      <Footer text='Blog'/>
      <Footer text='Status'/>
      <Footer text='Careers'/>
      <Footer text='Brands Resources'/>
      <Footer text='Advertising'/>
      <Footer text='Marketing'/>
      <Footer text='X for Business'/>
      <Footer text='Developers'/>
      <Footer text='Directory'/>
      <Footer text='Settings'/>
      <Footer text='© 2024 X Corp.'/>
    </>
  )
}
